<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-08-05T16:54:07 EET" name="Default suite" finished-at="2025-08-05T16:54:28 EET" duration-ms="21284">
    <groups>
    </groups>
    <test started-at="2025-08-05T16:54:07 EET" name="Default test" finished-at="2025-08-05T16:54:28 EET" duration-ms="21284">
      <class name="tests.UserTests">
        <test-method is-config="true" signature="setUp()[pri:0, instance:tests.UserTests@3e8c3cb]" started-at="2025-08-05T16:54:07 EET" name="setUp" finished-at="2025-08-05T16:54:11 EET" duration-ms="4169" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testSignUp()[pri:1, instance:tests.UserTests@3e8c3cb]" started-at="2025-08-05T16:54:11 EET" name="testSignUp" finished-at="2025-08-05T16:54:15 EET" duration-ms="3645" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Signup failed expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Signup failed expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertTrue(Assert.java:57)
at tests.UserTests.testSignUp(UserTests.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSignUp -->
        <test-method signature="testLogout()[pri:2, instance:tests.UserTests@3e8c3cb]" started-at="2025-08-05T16:54:15 EET" name="testLogout" finished-at="2025-08-05T16:54:15 EET" duration-ms="23" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogout -->
        <test-method signature="testLogIn()[pri:3, instance:tests.UserTests@3e8c3cb]" started-at="2025-08-05T16:54:15 EET" name="testLogIn" finished-at="2025-08-05T16:54:15 EET" depends-on-methods="tests.UserTests.testSignUp" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method tests.UserTests.testLogIn() on instance tests.UserTests@3e8c3cb depends on not successfully finished methods 
[tests.UserTests.testSignUp() on instance tests.UserTests@3e8c3cb]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method tests.UserTests.testLogIn() on instance tests.UserTests@3e8c3cb depends on not successfully finished methods 
[tests.UserTests.testSignUp() on instance tests.UserTests@3e8c3cb]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:159)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogIn -->
        <test-method signature="testaddToCardAndCheckout()[pri:4, instance:tests.UserTests@3e8c3cb]" started-at="2025-08-05T16:54:15 EET" name="testaddToCardAndCheckout" finished-at="2025-08-05T16:54:28 EET" duration-ms="13251" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testaddToCardAndCheckout -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:tests.UserTests@3e8c3cb]" started-at="2025-08-05T16:54:28 EET" name="teardown" finished-at="2025-08-05T16:54:28 EET" duration-ms="155" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- tests.UserTests -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
